config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      resources :reports, only:[:new, :create]
      resource :relationships, only:[:create, :destroy]
      get "relationships/followings" => "relationships#followings",as:"user_following"
      get "relationships/followers" => "relationships#followers",as:"user_follower"
    end
    resources :groups, only:[:new, :create, :index, :show, :destroy, :edit, :update]
      get "groups/:id/join" => "groups#join",as:"group_join"
      delete "groups/:id/leave" => "groups#leave",as:"group_leave"
    resources :group_messages, only:[:show, :create, :destroy]
    resources :posts, only:[:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only:[:create, :destroy]
      resource :post_favorites, only:[:create, :destroy]
    end
    resources :artists, only:[:index, :show] do
      resource :artist_favorites, only:[:create, :destroy]
    end
    resources :music_favorites, only:[:create, :destroy]
    resources :notifications, only:[:update]
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only:[:index, :show, :update]
    resources :posts, only:[:index, :destroy]
    resources :post_comments, only:[:index, :update]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :inappropriate_comments, only:[:new, :create, :destroy]
    resources :reports, only:[:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  default_scope -> {order(created_at: :desc)}

  belongs_to :user

  has_many :post_genres, dependent: :destroy
  has_many :genres, through: :post_genres

  has_many :post_favorites, dependent: :destroy
  has_many :favorite_users, through: :post_favorites, source: :user

  has_many :post_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_one_attached :post_image

  validates :title, presence: true, length: {maximum: 30}
  # :body_length = 改行のコードを除いた本文の文字数制限
  validate :body_length


  def body_length
    # 与えられたbodyの文字数(改行のコードは除外)を数える
    # bodyがnil(空)の場合はtext_lengthに0を代入
    text_length = body&.count("^\r\n") || 0
    errors.add(:body, "は40文字以内で入力してください") if text_length > 40
    errors.add(:body, "を入力してください") if text_length == 0
  end

  def get_post_image(width,height)
    # post_imageが存在しない場合'default.jpg'を保存
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/default.jpg')
      post_image.attach(io: File.open(file_path), filename: 'default.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_fill:[width,height])
  end

  def self.get_active_posts
    # ユーザーステータスが有効の投稿のみ表示
    self.joins(:user).where(users: { is_deleted: false })
  end

  def favorited_post_by?(user)
    post_favorites.where(user_id: user.id).exists?
  end

  def self.search_for(word)
    Post.where('title LIKE?',"%#{word}%").order(created_at: :desc)
  end

  def create_notification_like!(current_user)
    # すでにいいねされているかを検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'like'])
    #　いいねされていない場合にいいね通知を作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
        )
        # 自分の投稿に対するいいねは通知済みとする
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
    end
  end


  def create_notification_comment!(current_user, post_comment_id, visited_id)
    # ログインしているユーザーからのコメント通知を作成
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = case
    when params[:user_id]
      # 受け取ったユーザーIDの投稿を取得
      Post.where(user_id: params[:user_id])
    when params[:word]
      # 入力された文字に部分一致する投稿を取得
      Post.search_for(params[:word])
    else
      Post.all
    end
    @posts = @posts.page(params[:page]).per(20)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to request.referer, notice: "投稿を削除しました"
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-lg-12 d-flex justify-content-center">
      <h2>投稿一覧</h2>
    </div>
    
    <div class="col-lg-10 mx-auto">
      <table class="table table-sm text-center table-bordered table-striped">
        <thead class="bg-secondary text-white">
          <tr>
            <th scope="col" style="width: auto"></th>
            <th scope="col" style="width: 40%">タイトル</th>
            <th scope="col" style="width: auto">ユーザー</th>
            <th scope="col" style="width: auto">コメント</th>
            <th scope="col" style="width: auto">投稿日</th>
            <th scope="col" style="width: auto"></th>
          </tr>
        </thead>
        <tbody>
        <% @posts.each do |post| %>
          <tr class="text-secondary">
            <td class="align-middle"><%= image_tag post.get_post_image(30,30), class: "rounded-circle" %></td>
            <td class="align-middle"><%= post.title %></td>
            <td class="align-middle"><%= link_to post.user.name, admin_user_path(post.user) %></td>
            <td class="align-middle"><%= link_to post.post_comments.count, admin_post_comments_path(post_id: post.id) %></td>
            <td class="align-middle"><%= post.created_at.to_s(:datetime_jp) %></td>
            <td class="align-middle"><%= link_to "Delete", admin_post_path(post), method: :delete, class: "btn btn-outline-danger p-0 pr-1 pl-1" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @posts, class: "mx-auto" %>
    </div>
    
  </div>
</div>