config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      resources :reports, only:[:new, :create]
      resource :relationships, only:[:create, :destroy]
      get "relationships/followings" => "relationships#followings",as:"user_following"
      get "relationships/followers" => "relationships#followers",as:"user_follower"
    end
    resources :groups, only:[:new, :create, :index, :show, :destroy, :edit, :update]
      get "groups/:id/join" => "groups#join",as:"group_join"
      delete "groups/:id/leave" => "groups#leave",as:"group_leave"
    resources :group_messages, only:[:show, :create, :destroy]
    resources :posts, only:[:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only:[:create, :destroy]
      resource :post_favorites, only:[:create, :destroy]
    end
    resources :artists, only:[:index, :show] do
      resource :artist_favorites, only:[:create, :destroy]
    end
    resources :music_favorites, only:[:create, :destroy]
    resources :notifications, only:[:update]
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only:[:index, :show, :update]
    resources :posts, only:[:index, :destroy]
    resources :post_comments, only:[:index, :update]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :inappropriate_comments, only:[:new, :create, :destroy]
    resources :reports, only:[:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  
  has_many :notifications, dependent: :destroy

  validates :comment, presence: true, length: {maximum: 20}

  def self.search_for(word)
    PostComment.where('comment LIKE?',"%#{word}%").order(created_at: :desc)
  end

  def self.sort_by_deleted
    #作成日時が新しい順に表示し、論理削除済みのコメントは下の行に配置する
    self.all.order(is_deleted: :asc).order(created_at: :desc)
  end
  
  def self.with_inappropriate_comments
    #検索結果を入れる配列を用意
    post_comments = []
    #不適切なコメントを配列から取り出す
    InappropriateComment.pluck(:comment).each do |comment|
      #結果を配列へ追加していく
      post_comments.concat(where('comment LIKE ?', "%#{comment}%").order(created_at: :desc))
    end
    #上記の処理が完了した後に変数内の重複したidを除外
    post_comments.uniq(&:id)
  end

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @inappropriate_comments = InappropriateComment.all
    @inappropriate_comment = InappropriateComment.new
    @post_comments = case
    when params[:post_id]
      # 受け取った投稿IDに紐づくコメントを取得
      PostComment.where(post_id: params[:post_id])
    when params[:comment_id]
      # 不適切なワードに該当するコメントを取得
        post_comments = PostComment.with_inappropriate_comments
        Kaminari.paginate_array(post_comments)
    when params[:word]
      # 入力された文字に部分一致するコメントを取得
      PostComment.search_for(params[:word])
    else
      # 全ての投稿を取得(未削除のコメントを先頭に並び替え)
      PostComment.sort_by_deleted
    end
    @post_comments = @post_comments.page(params[:page]).per(20)
  end

  def update
    post_comment = PostComment.find(params[:id])
    # is_deletedをtrueに更新することで論理削除
    post_comment.update(is_deleted: true)
    redirect_to admin_post_comments_path, notice: "コメントを削除しました"
  end

end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<%= render 'public/shared/error_messages', resource: @inappropriate_comment %>
<div class="container">
  <div class="row">

    <div class="col-lg-12 d-flex justify-content-center">
      <h2>コメント一覧</h2>
    </div>
    <div class="col-lg-3">
      <div class="card">
        <div class="card-header font-weight-bold bg-secondary text-white text-center pt-1 pb-1">
          不適切なワード
        </div>
        <table class="table table-sm text-center table-bordered table-striped mb-0">
          <% @inappropriate_comments.each do |comment| %>
          <tr>
            <td class="align-middle" scope="col" style="width: 70%"><%= comment.comment %></td>
            <td><%= link_to "Delete", admin_inappropriate_comment_path(comment), method: :delete , class: "btn btn-outline-danger pl-1 pr-1 pt-0 pb-0" %></td>
          </tr>
          <% end %>
        </table>
        <div class="card-footer text-center">
        <%= link_to "不適切なコメントを検索", admin_post_comments_path(comment_id: 1), class: "btn btn-info" %>
        </div>
      </div>
      <div class="card mt-3">
        <div class="card-header bg-secondary text-white text-center font-weight-bold">
          不適切なワードを追加
        </div>
        <%= form_with model: @inappropriate_comment, url: admin_inappropriate_comments_path, method: :post do |f| %>
        <div class="form-group mt-5 mr-4 ml-4">
            <%= f.label :comment %>
            <%= f.text_field :comment, class: "form-control" %>
        </div>
        <div class="form-group text-center mb-5 mt-5">
          <%= f.submit "追加", class: "btn btn-outline-success pl-5 pr-5" %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-9">
      <table class="table table-sm text-center table-bordered table-striped">
        <thead class="bg-secondary text-white">
          <tr>
            <th scope="col" style="width: auto">投稿タイトル</th>
            <th scope="col" style="width: auto">コメント</th>
            <th scope="col" style="width: auto">ユーザーネーム</th>
            <th scope="col" style="width: auto">作成日</th>
            <th scope="col" style="width: auto">ステータス</th>
            <th scope="col" style="width: auto"></th>
          </tr>
        </thead>
        <tbody>
        <% @post_comments.each do |post_comment| %>
          <tr class="text-secondary">
            <td class="align-middle"><%= post_comment.post.title %></td>
            <td class="align-middle"><%= post_comment.comment %></td>
            <td class="align-middle"><%= link_to post_comment.user.name, admin_user_path(post_comment.user), class: "text-secondary" %></td>
            <td class="align-middle"><%= post_comment.created_at.to_s(:datetime_jp) %></td>
            <td class="align-middle">
              <% if post_comment.is_deleted == false %>
                <p class="m-0 text-info">有効</p>
              <% else %>
                <p class="m-0 text-danger">削除済み</p>
              <% end %>
            </td>
            <td class="align-middle"><%= link_to "Delete", admin_post_comment_path(post_comment), method: :patch, class: "btn btn-outline-danger p-0 pr-1 pl-1" %></td>
          </tr>
      <% end %>
        </tbody>
      </table>
      <%= paginate @post_comments, class: "mx-auto" %>
    </div>

  </div>
</div>