config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      resources :reports, only:[:new, :create]
      resource :relationships, only:[:create, :destroy]
      get "relationships/followings" => "relationships#followings",as:"user_following"
      get "relationships/followers" => "relationships#followers",as:"user_follower"
    end
    resources :groups, only:[:new, :create, :index, :show, :destroy, :edit, :update]
      get "groups/:id/join" => "groups#join",as:"group_join"
      delete "groups/:id/leave" => "groups#leave",as:"group_leave"
    resources :group_messages, only:[:show, :create, :destroy]
    resources :posts, only:[:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only:[:create, :destroy]
      resource :post_favorites, only:[:create, :destroy]
    end
    resources :artists, only:[:index, :show] do
      resource :artist_favorites, only:[:create, :destroy]
    end
    resources :music_favorites, only:[:create, :destroy]
    resources :notifications, only:[:update]
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only:[:index, :show, :update]
    resources :posts, only:[:index, :destroy]
    resources :post_comments, only:[:index, :update]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :inappropriate_comments, only:[:new, :create, :destroy]
    resources :reports, only:[:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord

  default_scope -> {order(created_at: :desc)}
  #reporter => 通報者
  belongs_to :reporter, class_name: "User"
  #reported => 通報される人
  belongs_to :reported, class_name: "User"

  enum status: {waiting: 0, keep: 1, finish: 2}
  
  validates :reason, presence: true
  validates :url, presence: true
  
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController

  def index
    @reports = Report.page(params[:page]).per(20)
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to request.referer, notice: "対応ステータスを更新しました。"
    end
  end

  private

  def report_params
    params.require(:report).permit(:status)
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 d-flex justify-content-center">
      <h2>通報一覧</h2>
    </div>
    <div class="col-lg-10 mx-auto">
      <table class="table table-sm text-center table-bordered table-striped">
        <thead class="bg-secondary text-white">
          <tr>
            <th scope="col" style="width: auto">通報ID</th>
            <th scope="col" style="width: auto">会員名</th>
            <th scope="col" style="width: auto">通報者</th>
            <th scope="col" style="width: auto">ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @reports.each do |report| %>
          <tr class="text-secondary">
            <td class="align-middle"><%= link_to report.id, admin_report_path(report) %></td>
            <td class="align-middle"><%= report.reported.name %></td>
            <td class="align-middle"><%= report.reporter.name %></td>
            <td class="align-middle"><%= report.status_i18n %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @reports, class: "mx-auto" %>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-lg-8 mx-auto">
      <h2 class="text-center">ユーザー詳細</h2>
      <table class="table table-bordered">
        <tr>
          <th  scope="col" class="bg-secondary text-white" style="width: 30%">通報ID</th>
          <td><%= @report.id %></td>
        </tr>
        <tr>
          <th class="bg-secondary text-white">会員名</th>
          <td><%= @report.reported.name %></td>
        </tr>
        <tr>
          <th class="bg-secondary text-white">理由</th>
          <td><%= @report.reason %></td>
        </tr>
        <tr>
          <th class="bg-secondary text-white">URL</th>
          <td><%= link_to @report.url %></td>
        </tr>
        <tr>
          <th class="bg-secondary text-white">通報者</th>
          <td><%= @report.reporter.name %></td>
        </tr>
        <tr>
          <th class="bg-secondary text-white">対応ステータス</th>
          <td>
            <%= @report.status_i18n %>
            <%= form_with model: @report, url:admin_report_path(@report), method: :patch, local: true do |f| %>
              <%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] } %>
              <%= f.submit '更新' %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    
    <div class="col-lg-5 mx-auto">
      <%= link_to "通報一覧", admin_reports_path, class: "btn btn-info btn-block" %>
    </div>
    
  </div>
</div>