config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      resources :reports, only:[:new, :create]
      resource :relationships, only:[:create, :destroy]
      get "relationships/followings" => "relationships#followings",as:"user_following"
      get "relationships/followers" => "relationships#followers",as:"user_follower"
    end
    resources :groups, only:[:new, :create, :index, :show, :destroy, :edit, :update]
      get "groups/:id/join" => "groups#join",as:"group_join"
      delete "groups/:id/leave" => "groups#leave",as:"group_leave"
    resources :group_messages, only:[:show, :create, :destroy]
    resources :posts, only:[:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only:[:create, :destroy]
      resource :post_favorites, only:[:create, :destroy]
    end
    resources :artists, only:[:index, :show] do
      resource :artist_favorites, only:[:create, :destroy]
    end
    resources :music_favorites, only:[:create, :destroy]
    resources :notifications, only:[:update]
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :users, only:[:index, :show, :update]
    resources :posts, only:[:index, :destroy]
    resources :post_comments, only:[:index, :update]
    resources :genres, only:[:new, :index, :create, :edit, :update, :destroy]
    resources :inappropriate_comments, only:[:new, :create, :destroy]
    resources :reports, only:[:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admins_header.html.erb
<div class="col-1 p-0 text-center">
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Log_out", destroy_admin_session_path, method: :delete, class: "text-white" %>
</div>
<div class="col-3 p-0 mx-auto">
  <%= render 'admin/search' %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Genres", admin_genres_path, class: "text-white" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Posts", admin_posts_path, class: "text-white" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Users", admin_users_path, class: "text-white" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Comments", admin_post_comments_path, class: "text-white" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Reports", admin_reports_path, class: "text-white" %>
</div>

app/views/layouts/_check_icon.html.erb
<% if current_user.passive_notifications.where(checked: false).count > 0 %>
  <i class="fas fa-circle position-absolute top-3 start-4" style="top: 17px; right: 17px; color:#ffb204"></i>
<% end %>

app/views/layouts/_logout_header.html.erb
<div class="col-1 p-0 text-center head">
  <%= link_to "Sign up", new_user_registration_path, class: "text-light font-weight-bold" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Log in", new_user_session_path, class: "text-light font-weight-bold" %>
</div>

app/views/layouts/_users_header.html.erb
<div class="col-1 p-0 text-center position-relative">
  <%= link_to user_path(current_user) do %>
    <%= image_tag current_user.get_profile_image(30,30), class: "rounded-circle" %>
  <% end %>
  <div id="checked">
    <%= render "layouts/check_icon" %>
  </div>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-light font-weight-bold" %>
</div>
<div class="col-4 p-0 mx-auto">
  <% if current_page?(posts_path) %>
    <%= render 'public/posts/search_post' %>
  <% elsif current_page?(users_path) %>
    <%= render 'public/users/search_user' %>
  <% elsif current_page?(groups_path) %>
    <%= render 'public/groups/search_group' %>
  <% else %>
    <%= render 'public/artists/search_artist' %>
  <% end %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Artists", artists_path, class: "text-light font-weight-bold" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Posts", posts_path, class: "text-light font-weight-bold" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Users", users_path, class: "text-light font-weight-bold" %>
</div>
<div class="col-1 p-0 text-center head">
  <%= link_to "Groups", groups_path, class: "text-light font-weight-bold" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mu_Link</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">

    <header class="sticky-top alegreya">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 pt-0 pb-0">
        <div class="col-2 p-0 text-center d-flex">
          <% if user_signed_in? %>
          <div id="sp-menu">
            <h2 class="font-weight-bold text-white text-shadow">MENU</h2>
            <ul>
              <li><%= link_to "New post", new_post_path, class: "text-white text-shadow" %></li>
              <li><%= link_to "New group", new_group_path, class: "text-white text-shadow" %></li>
              <li><%= link_to "Your group", groups_path(user_id: current_user.id), class: "text-white text-shadow" %></li>
              <li><%= link_to "Your favorite posts", posts_path(liked_post_id: current_user.id), class: "text-white text-shadow" %></li>
            </ul>
          </div>
          <div id="hm-icon" class="position-relative">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
          <% end %>
          <% if admin_signed_in? %>
            <a class="navbar-brand pt-0 pb-0" href="/admin"><%= image_tag 'mu_link.png', style: "width: 100px" %></a>
          <% else %>
            <a class="navbar-brand pt-0 pb-0 mx-auto" href="/"><%= image_tag 'mu_link.png', style: "width: 100px" %></a>
          <% end %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if user_signed_in? %>
            <%= render 'layouts/users_header' %>
          <% elsif admin_signed_in? %>
            <%= render 'layouts/admins_header' %>
          <% else %>
            <%= render 'layouts/logout_header' %>
          <% end %>
        </div>
      </nav>
    </header>

    <main class="mb-3">
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </main>

    <footer class="footer py-3 bg-dark mt-auto" style="height: 100px;">
      <div class="container h-100 align-middle">
        <div class="text-center">
          <div class="mt-3">
          <p class="text-center text-white" style="line-height: 1;">Mu_link</p>
          </div>
          <div class="mt-2 mr-4">
       　  <span class="copyright text-white text-cente align-middle" style="line-height: 1; font-size: 10px;">
         　<%= image_tag 'spotify.png', style: "width: 60px" %>
          </span>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>